//contains data from each file provided 

const modeLessThan5km = {
    "Data": [
            {
                "Choice situation": 1.0,
                "mode_1": "Bus Type 1",
                "mode_1.ivtt": 13,
                "mode_1.tcost": 14,
                "mode_1.walktime": 3,
                "mode_1.waittime": 4,
                "mode_1.tvariab": 2,
                "mode_1.trans": 0,
                "mode_1.crowd": 2,
                "mode_1.serv": 1,
                "mode_2": "Bus Type 2",
                "mode_2.ivtt": 12,
                "mode_2.tcost": 25,
                "mode_2.walktime": 3,
                "mode_2.waittime": 4,
                "mode_2.tvariab": 3,
                "mode_2.trans": 0,
                "mode_2.crowd": 2,
                "mode_2.serv": 2,
                "mode_4": "Walk / Bicycle",
                "mode_4.ivtt": 65,
                "mode_4.tcost": 0,
                "mode_4.walktime": 0,
                "mode_4.waittime": 0,
                "mode_4.tvariab": 0,
                "mode_4.trans": 0,
                "mode_4.crowd": 0,
                "mode_4.serv": 0,
                "mode_5": "Ride-hailing Car",
                "mode_5.ivtt": 15,
                "mode_5.tcost": 75,
                "mode_5.walktime": 2,
                "mode_5.waittime": 6,
                "mode_5.tvariab": 1,
                "mode_5.trans": 0,
                "mode_5.crowd": 0,
                "mode_5.serv": 0,
                "mode_6": "Ride-hailing Two-wheeler",
                "mode_6.ivtt": 9,
                "mode_6.tcost": 8,
                "mode_6.walktime": 2,
                "mode_6.waittime": 4,
                "mode_6.tvariab": 1,
                "mode_6.trans": 0,
                "mode_6.crowd": 0,
                "mode_6.serv": 0,
                "mode_7": "Auto",
                "mode_7.ivtt": 14,
                "mode_7.tcost": 35,
                "mode_7.walktime": 2,
                "mode_7.waittime": 4,
                "mode_7.tvariab": 3,
                "mode_7.trans": 0,
                "mode_7.crowd": 0,
                "mode_7.serv": 0,
                "mode_8": "Own Car",
                "mode_8.ivtt": 12,
                "mode_8.tcost": 15,
                "mode_8.walktime": 0,
                "mode_8.waittime": 0,
                "mode_8.tvariab": 8,
                "mode_8.trans": 0,
                "mode_8.crowd": 0,
                "mode_8.serv": 0,
                "mode_9": "Own Two-wheeler",
                "mode_9.ivtt": 13,
                "mode_9.tcost": 12,
                "mode_9.walktime": 0,
                "mode_9.waittime": 0,
                "mode_9.tvariab": 6,
                "mode_9.trans": 0,
                "mode_9.crowd": 0,
                "mode_9.serv": 0
            }
   ]
}

const modeLessThan10km = {
    "Data": [
            {
                "Choice situation": 17.0,
                "mode_1": "Bus Type 1",
                "mode_1.ivtt": 16,
                "mode_1.tcost": 17,
                "mode_1.walktime": 4,
                "mode_1.waittime": 7,
                "mode_1.tvariab": 8,
                "mode_1.trans": 0,
                "mode_1.crowd": 3,
                "mode_1.serv": 1,
                "mode_2": "Bus Type 2",
                "mode_2.ivtt": 19,
                "mode_2.tcost": 40,
                "mode_2.walktime": 4,
                "mode_2.waittime": 6,
                "mode_2.tvariab": 6,
                "mode_2.trans": 0,
                "mode_2.crowd": 1,
                "mode_2.serv": 2,
                "mode_3": "Bus Type 3",
                "mode_3.ivtt": 15,
                "mode_3.tcost": 50,
                "mode_3.walktime": 4,
                "mode_3.waittime": 6,
                "mode_3.tvariab": 4,
                "mode_3.trans": 0,
                "mode_3.crowd": 3,
                "mode_3.serv": 3,
                "mode_4": "Metro / Train",
                "mode_4.ivtt": 16,
                "mode_4.tcost": 30,
                "mode_4.walktime": 5,
                "mode_4.waittime": 4,
                "mode_4.tvariab": 3,
                "mode_4.trans": 0,
                "mode_4.crowd": 3,
                "mode_4.serv": 0,
                "mode_5": "Ride-hailing Car",
                "mode_5.ivtt": 15,
                "mode_5.tcost": 140,
                "mode_5.walktime": 3,
                "mode_5.waittime": 6,
                "mode_5.tvariab": 5,
                "mode_5.trans": 0,
                "mode_5.crowd": 0,
                "mode_5.serv": 0,
                "mode_6": "Ride-hailing Two-wheeler",
                "mode_6.ivtt": 12,
                "mode_6.tcost": 13,
                "mode_6.walktime": 2,
                "mode_6.waittime": 6,
                "mode_6.tvariab": 3,
                "mode_6.trans": 0,
                "mode_6.crowd": 0,
                "mode_6.serv": 0,
                "mode_7": "Auto",
                "mode_7.ivtt": 24,
                "mode_7.tcost": 73,
                "mode_7.walktime": 3,
                "mode_7.waittime": 6,
                "mode_7.tvariab": 7,
                "mode_7.trans": 0,
                "mode_7.crowd": 0,
                "mode_7.serv": 0,
                "mode_8": "Own Car",
                "mode_8.ivtt": 13,
                "mode_8.tcost": 28,
                "mode_8.walktime": 0,
                "mode_8.waittime": 0,
                "mode_8.tvariab": 9,
                "mode_8.trans": 0,
                "mode_8.crowd": 0,
                "mode_8.serv": 0,
                "mode_9": "Own Two-wheeler",
                "mode_9.ivtt": 13,
                "mode_9.tcost": 16,
                "mode_9.walktime": 0,
                "mode_9.waittime": 0,
                "mode_9.tvariab": 4,
                "mode_9.trans": 0,
                "mode_9.crowd": 0,
                "mode_9.serv": 0
            }
   ]
}

const modeLessThan15km = {
    "Data": [
            {
                "Choice situation": 5.0,
                "mode_1": "Bus Type 1",
                "mode_1.ivtt": 45,
                "mode_1.tcost": 19,
                "mode_1.walktime": 7,
                "mode_1.waittime": 11,
                "mode_1.tvariab": 9,
                "mode_1.trans": 1,
                "mode_1.crowd": 1,
                "mode_1.serv": 1,
                "mode_2": "Bus Type 2",
                "mode_2.ivtt": 37,
                "mode_2.tcost": 45,
                "mode_2.walktime": 6,
                "mode_2.waittime": 10,
                "mode_2.tvariab": 7,
                "mode_2.trans": 0,
                "mode_2.crowd": 4,
                "mode_2.serv": 2,
                "mode_3": "Bus Type 3",
                "mode_3.ivtt": 27,
                "mode_3.tcost": 83,
                "mode_3.walktime": 6,
                "mode_3.waittime": 10,
                "mode_3.tvariab": 8,
                "mode_3.trans": 0,
                "mode_3.crowd": 3,
                "mode_3.serv": 3,
                "mode_4": "Metro / Train",
                "mode_4.ivtt": 21,
                "mode_4.tcost": 33,
                "mode_4.walktime": 4,
                "mode_4.waittime": 9,
                "mode_4.tvariab": 2,
                "mode_4.trans": 0,
                "mode_4.crowd": 4,
                "mode_4.serv": 0,
                "mode_5": "Ride-hailing Car",
                "mode_5.ivtt": 22,
                "mode_5.tcost": 231,
                "mode_5.walktime": 3,
                "mode_5.waittime": 6,
                "mode_5.tvariab": 8,
                "mode_5.trans": 0,
                "mode_5.crowd": 0,
                "mode_5.serv": 0,
                "mode_6": "Ride-hailing Two-wheeler",
                "mode_6.ivtt": 27,
                "mode_6.tcost": 25,
                "mode_6.walktime": 6,
                "mode_6.waittime": 3,
                "mode_6.tvariab": 6,
                "mode_6.trans": 0,
                "mode_6.crowd": 0,
                "mode_6.serv": 0,
                "mode_7": "Auto",
                "mode_7.ivtt": 31,
                "mode_7.tcost": 122,
                "mode_7.walktime": 3,
                "mode_7.waittime": 6,
                "mode_7.tvariab": 9,
                "mode_7.trans": 0,
                "mode_7.crowd": 0,
                "mode_7.serv": 0,
                "mode_8": "Own Car",
                "mode_8.ivtt": 20,
                "mode_8.tcost": 51,
                "mode_8.walktime": 0,
                "mode_8.waittime": 0,
                "mode_8.tvariab": 14,
                "mode_8.trans": 0,
                "mode_8.crowd": 0,
                "mode_8.serv": 0,
                "mode_9": "Own Two-wheeler",
                "mode_9.ivtt": 27,
                "mode_9.tcost": 26,
                "mode_9.walktime": 0,
                "mode_9.waittime": 0,
                "mode_9.tvariab": 5,
                "mode_9.trans": 0,
                "mode_9.crowd": 0,
                "mode_9.serv": 0
            }
   ]
}

const modeLessThan20km = {
    "Data": [
            {
                "Choice situation": 1.0,
                "mode_1": "Bus Type 1",
                "mode_1.ivtt": 51,
                "mode_1.tcost": 20,
                "mode_1.walktime": 7,
                "mode_1.waittime": 10,
                "mode_1.tvariab": 15,
                "mode_1.trans": 1,
                "mode_1.crowd": 2,
                "mode_1.serv": 1,
                "mode_2": "Bus Type 2",
                "mode_2.ivtt": 40,
                "mode_2.tcost": 53,
                "mode_2.walktime": 7,
                "mode_2.waittime": 10,
                "mode_2.tvariab": 9,
                "mode_2.trans": 0,
                "mode_2.crowd": 2,
                "mode_2.serv": 2,
                "mode_4": "Metro / Train",
                "mode_4.ivtt": 25,
                "mode_4.tcost": 40,
                "mode_4.walktime": 6,
                "mode_4.waittime": 14,
                "mode_4.tvariab": 3,
                "mode_4.trans": 0,
                "mode_4.crowd": 1,
                "mode_4.serv": 0,
                "mode_5": "Ride-hailing Car",
                "mode_5.ivtt": 33,
                "mode_5.tcost": 310,
                "mode_5.walktime": 6,
                "mode_5.waittime": 2,
                "mode_5.tvariab": 12,
                "mode_5.trans": 0,
                "mode_5.crowd": 0,
                "mode_5.serv": 0,
                "mode_6": "Ride-hailing Two-wheeler",
                "mode_6.ivtt": 26,
                "mode_6.tcost": 11,
                "mode_6.walktime": 4,
                "mode_6.waittime": 10,
                "mode_6.tvariab": 10,
                "mode_6.trans": 0,
                "mode_6.crowd": 0,
                "mode_6.serv": 0,
                "mode_7": "Auto",
                "mode_7.ivtt": 49,
                "mode_7.tcost": 171,
                "mode_7.walktime": 3,
                "mode_7.waittime": 8,
                "mode_7.tvariab": 13,
                "mode_7.trans": 0,
                "mode_7.crowd": 0,
                "mode_7.serv": 0,
                "mode_8": "Own Car",
                "mode_8.ivtt": 32,
                "mode_8.tcost": 90,
                "mode_8.walktime": 0,
                "mode_8.waittime": 0,
                "mode_8.tvariab": 14,
                "mode_8.trans": 0,
                "mode_8.crowd": 0,
                "mode_8.serv": 0,
                "mode_9": "Own Two-wheeler",
                "mode_9.ivtt": 28,
                "mode_9.tcost": 36,
                "mode_9.walktime": 0,
                "mode_9.waittime": 0,
                "mode_9.tvariab": 10,
                "mode_9.trans": 0,
                "mode_9.crowd": 0,
                "mode_9.serv": 0
            }
        ]
}


const modeLessThan25km = {
    "Data": [
            {
                "Choice situation": 1.0,
                "mode_1": "Bus Type 1",
                "mode_1.ivtt": 68,
                "mode_1.tcost": 30,
                "mode_1.walktime": 8,
                "mode_1.waittime": 12,
                "mode_1.tvariab": 21,
                "mode_1.trans": 1,
                "mode_1.crowd": 1,
                "mode_1.serv": 1,
                "mode_2": "Bus Type 2",
                "mode_2.ivtt": 52,
                "mode_2.tcost": 60,
                "mode_2.walktime": 8,
                "mode_2.waittime": 12,
                "mode_2.tvariab": 18,
                "mode_2.trans": 0,
                "mode_2.crowd": 2,
                "mode_2.serv": 2,
                "mode_4": "Metro / Train",
                "mode_4.ivtt": 31,
                "mode_4.tcost": 58,
                "mode_4.walktime": 8,
                "mode_4.waittime": 18,
                "mode_4.tvariab": 5,
                "mode_4.trans": 0,
                "mode_4.crowd": 2,
                "mode_4.serv": 0,
                "mode_5": "Ride-hailing Car",
                "mode_5.ivtt": 39,
                "mode_5.tcost": 380,
                "mode_5.walktime": 5,
                "mode_5.waittime": 3,
                "mode_5.tvariab": 14,
                "mode_5.trans": 0,
                "mode_5.crowd": 0,
                "mode_5.serv": 0,
                "mode_6": "Ride-hailing Two-wheeler",
                "mode_6.ivtt": 43,
                "mode_6.tcost": 17,
                "mode_6.walktime": 4,
                "mode_6.waittime": 10,
                "mode_6.tvariab": 15,
                "mode_6.trans": 0,
                "mode_6.crowd": 0,
                "mode_6.serv": 0,
                "mode_7": "Auto",
                "mode_7.ivtt": 61,
                "mode_7.tcost": 219,
                "mode_7.walktime": 4,
                "mode_7.waittime": 9,
                "mode_7.tvariab": 14,
                "mode_7.trans": 0,
                "mode_7.crowd": 0,
                "mode_7.serv": 0,
                "mode_8": "Own Car",
                "mode_8.ivtt": 43,
                "mode_8.tcost": 120,
                "mode_8.walktime": 0,
                "mode_8.waittime": 0,
                "mode_8.tvariab": 24,
                "mode_8.trans": 0,
                "mode_8.crowd": 0,
                "mode_8.serv": 0,
                "mode_9": "Own Two-wheeler",
                "mode_9.ivtt": 36,
                "mode_9.tcost": 45,
                "mode_9.walktime": 0,
                "mode_9.waittime": 0,
                "mode_9.tvariab": 20,
                "mode_9.trans": 0,
                "mode_9.crowd": 0,
                "mode_9.serv": 0
            }
   ]
}

const modeMoreThan25km = {
    "Data": [
            {
                "Choice situation": 1.0,
                "mode_1": "Bus Type 1",
                "mode_1.ivtt": 85,
                "mode_1.tcost": 32,
                "mode_1.walktime": 8,
                "mode_1.waittime": 12,
                "mode_1.tvariab": 24,
                "mode_1.trans": 1,
                "mode_1.crowd": 2,
                "mode_1.serv": 1,
                "mode_2": "Bus Type 2",
                "mode_2.ivtt": 70,
                "mode_2.tcost": 68,
                "mode_2.walktime": 9,
                "mode_2.waittime": 13,
                "mode_2.tvariab": 16,
                "mode_2.trans": 0,
                "mode_2.crowd": 4,
                "mode_2.serv": 2,
                "mode_3": "Bus Type 3",
                "mode_3.ivtt": 75,
                "mode_3.tcost": 95,
                "mode_3.walktime": 10,
                "mode_3.waittime": 14,
                "mode_3.tvariab": 16,
                "mode_3.trans": 0,
                "mode_3.crowd": 4,
                "mode_3.serv": 3,
                "mode_4": "Metro / Train",
                "mode_4.ivtt": 42,
                "mode_4.tcost": 55,
                "mode_4.walktime": 8,
                "mode_4.waittime": 19,
                "mode_4.tvariab": 6,
                "mode_4.trans": 0,
                "mode_4.crowd": 4,
                "mode_4.serv": 0,
                "mode_5": "Ride-hailing Car",
                "mode_5.ivtt": 63,
                "mode_5.tcost": 425,
                "mode_5.walktime": 6,
                "mode_5.waittime": 3,
                "mode_5.tvariab": 14,
                "mode_5.trans": 0,
                "mode_5.crowd": 0,
                "mode_5.serv": 0,
                "mode_6": "Ride-hailing Two-wheeler",
                "mode_6.ivtt": 54,
                "mode_6.tcost": 26,
                "mode_6.walktime": 8,
                "mode_6.waittime": 12,
                "mode_6.tvariab": 20,
                "mode_6.trans": 0,
                "mode_6.crowd": 0,
                "mode_6.serv": 0,
                "mode_7": "Auto",
                "mode_7.ivtt": 57,
                "mode_7.tcost": 268,
                "mode_7.walktime": 4,
                "mode_7.waittime": 10,
                "mode_7.tvariab": 15,
                "mode_7.trans": 0,
                "mode_7.crowd": 0,
                "mode_7.serv": 0,
                "mode_8": "Own Car",
                "mode_8.ivtt": 55,
                "mode_8.tcost": 150,
                "mode_8.walktime": 0,
                "mode_8.waittime": 0,
                "mode_8.tvariab": 35,
                "mode_8.trans": 0,
                "mode_8.crowd": 0,
                "mode_8.serv": 0,
                "mode_9": "Own Two-wheeler",
                "mode_9.ivtt": 47,
                "mode_9.tcost": 58,
                "mode_9.walktime": 0,
                "mode_9.waittime": 0,
                "mode_9.tvariab": 30,
                "mode_9.trans": 0,
                "mode_9.crowd": 0,
                "mode_9.serv": 0
            }
   ]
}

export {modeMoreThan25km,modeLessThan25km,modeLessThan20km,modeLessThan15km,modeLessThan10km,modeLessThan5km}